### ISSUE TITLE
canvas-wave の表示位置がズレる

### ISSUE THREAD

**Issue by Squ4t4r014** [Squ4t4r014/zura-chan-zura#114]

**Comment by t4t5u0** [comment]
style.scss では

```css
canvas {
    position: fixed;
    display: flex;
    right: 0;
    bottom: 0;
    width: max-content;
    height: 15vh;
}
```

で高さが定義されているが，


bundle.ts では，

```
canvas.height = 300;
```

と定義されている．

15vhが優先されてしまい，Canvasの縦横比が保持されたまた縦が縮むため波の横幅が

```
100vw * (300 / 15vh)
```

になってると推測される．
